name: mobile_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

 
  fonts:
    - family: Visby
      fonts:
        - asset: assets/fonts/VisbyCF-Medium.otf
        - asset: assets/fonts/VisbyCF-Bold.otf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  